#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_QuanLy_San_Bong_Mini
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SANBONGMINI1")]
	public partial class DataClassesTestDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGIAGIOTHUE(GIAGIOTHUE instance);
    partial void UpdateGIAGIOTHUE(GIAGIOTHUE instance);
    partial void DeleteGIAGIOTHUE(GIAGIOTHUE instance);
    partial void InsertHDTHANHTOAN(HDTHANHTOAN instance);
    partial void UpdateHDTHANHTOAN(HDTHANHTOAN instance);
    partial void DeleteHDTHANHTOAN(HDTHANHTOAN instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHIEUDATSAN(PHIEUDATSAN instance);
    partial void UpdatePHIEUDATSAN(PHIEUDATSAN instance);
    partial void DeletePHIEUDATSAN(PHIEUDATSAN instance);
    partial void InsertSANBONG(SANBONG instance);
    partial void UpdateSANBONG(SANBONG instance);
    partial void DeleteSANBONG(SANBONG instance);
    #endregion
		
		public DataClassesTestDataContext() : 
				base(global::Do_An_QuanLy_San_Bong_Mini.Properties.Settings.Default.SANBONGMINI1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTestDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GIAGIOTHUE> GIAGIOTHUEs
		{
			get
			{
				return this.GetTable<GIAGIOTHUE>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<HDTHANHTOAN> HDTHANHTOANs
		{
			get
			{
				return this.GetTable<HDTHANHTOAN>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDATSAN> PHIEUDATSANs
		{
			get
			{
				return this.GetTable<PHIEUDATSAN>();
			}
		}
		
		public System.Data.Linq.Table<SANBONG> SANBONGs
		{
			get
			{
				return this.GetTable<SANBONG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAGIOTHUE")]
	public partial class GIAGIOTHUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Magio;
		
		private string _Chitiet;
		
		private decimal _Dongia;
		
		private EntitySet<PHIEUDATSAN> _PHIEUDATSANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMagioChanging(string value);
    partial void OnMagioChanged();
    partial void OnChitietChanging(string value);
    partial void OnChitietChanged();
    partial void OnDongiaChanging(decimal value);
    partial void OnDongiaChanged();
    #endregion
		
		public GIAGIOTHUE()
		{
			this._PHIEUDATSANs = new EntitySet<PHIEUDATSAN>(new Action<PHIEUDATSAN>(this.attach_PHIEUDATSANs), new Action<PHIEUDATSAN>(this.detach_PHIEUDATSANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magio", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Magio
		{
			get
			{
				return this._Magio;
			}
			set
			{
				if ((this._Magio != value))
				{
					this.OnMagioChanging(value);
					this.SendPropertyChanging();
					this._Magio = value;
					this.SendPropertyChanged("Magio");
					this.OnMagioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chitiet", DbType="NVarChar(50)")]
		public string Chitiet
		{
			get
			{
				return this._Chitiet;
			}
			set
			{
				if ((this._Chitiet != value))
				{
					this.OnChitietChanging(value);
					this.SendPropertyChanging();
					this._Chitiet = value;
					this.SendPropertyChanged("Chitiet");
					this.OnChitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Decimal(18,0) NOT NULL")]
		public decimal Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAGIOTHUE_PHIEUDATSAN", Storage="_PHIEUDATSANs", ThisKey="Magio", OtherKey="Magio")]
		public EntitySet<PHIEUDATSAN> PHIEUDATSANs
		{
			get
			{
				return this._PHIEUDATSANs;
			}
			set
			{
				this._PHIEUDATSANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.GIAGIOTHUE = this;
		}
		
		private void detach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.GIAGIOTHUE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN
	{
		
		private string _Tendangnhap;
		
		private string _MADN;
		
		private string _Pass;
		
		public TAIKHOAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendangnhap", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Tendangnhap
		{
			get
			{
				return this._Tendangnhap;
			}
			set
			{
				if ((this._Tendangnhap != value))
				{
					this._Tendangnhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADN", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MADN
		{
			get
			{
				return this._MADN;
			}
			set
			{
				if ((this._MADN != value))
				{
					this._MADN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HDTHANHTOAN")]
	public partial class HDTHANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoHDTT;
		
		private System.Nullable<int> _MaPDS;
		
		private string _MaKH;
		
		private string _MaNV;
		
		private System.Nullable<System.DateTime> _Ngaylap;
		
		private System.Nullable<decimal> _thanhtien;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<PHIEUDATSAN> _PHIEUDATSAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHDTTChanging(int value);
    partial void OnSoHDTTChanged();
    partial void OnMaPDSChanging(System.Nullable<int> value);
    partial void OnMaPDSChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnNgaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaylapChanged();
    partial void OnthanhtienChanging(System.Nullable<decimal> value);
    partial void OnthanhtienChanged();
    #endregion
		
		public HDTHANHTOAN()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._PHIEUDATSAN = default(EntityRef<PHIEUDATSAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHDTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SoHDTT
		{
			get
			{
				return this._SoHDTT;
			}
			set
			{
				if ((this._SoHDTT != value))
				{
					this.OnSoHDTTChanging(value);
					this.SendPropertyChanging();
					this._SoHDTT = value;
					this.SendPropertyChanged("SoHDTT");
					this.OnSoHDTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPDS", DbType="Int")]
		public System.Nullable<int> MaPDS
		{
			get
			{
				return this._MaPDS;
			}
			set
			{
				if ((this._MaPDS != value))
				{
					if (this._PHIEUDATSAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPDSChanging(value);
					this.SendPropertyChanging();
					this._MaPDS = value;
					this.SendPropertyChanged("MaPDS");
					this.OnMaPDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylap", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaylap
		{
			get
			{
				return this._Ngaylap;
			}
			set
			{
				if ((this._Ngaylap != value))
				{
					this.OnNgaylapChanging(value);
					this.SendPropertyChanging();
					this._Ngaylap = value;
					this.SendPropertyChanged("Ngaylap");
					this.OnNgaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HDTHANHTOAN", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HDTHANHTOANs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HDTHANHTOANs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HDTHANHTOAN", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HDTHANHTOANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HDTHANHTOANs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDATSAN_HDTHANHTOAN", Storage="_PHIEUDATSAN", ThisKey="MaPDS", OtherKey="MaPDS", IsForeignKey=true, DeleteRule="CASCADE")]
		public PHIEUDATSAN PHIEUDATSAN
		{
			get
			{
				return this._PHIEUDATSAN.Entity;
			}
			set
			{
				PHIEUDATSAN previousValue = this._PHIEUDATSAN.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDATSAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDATSAN.Entity = null;
						previousValue.HDTHANHTOANs.Remove(this);
					}
					this._PHIEUDATSAN.Entity = value;
					if ((value != null))
					{
						value.HDTHANHTOANs.Add(this);
						this._MaPDS = value.MaPDS;
					}
					else
					{
						this._MaPDS = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHIEUDATSAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _Gioitinh;
		
		private string _SDT;
		
		private string _Ghichu;
		
		private EntitySet<HDTHANHTOAN> _HDTHANHTOANs;
		
		private EntitySet<PHIEUDATSAN> _PHIEUDATSANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HDTHANHTOANs = new EntitySet<HDTHANHTOAN>(new Action<HDTHANHTOAN>(this.attach_HDTHANHTOANs), new Action<HDTHANHTOAN>(this.detach_HDTHANHTOANs));
			this._PHIEUDATSANs = new EntitySet<PHIEUDATSAN>(new Action<PHIEUDATSAN>(this.attach_PHIEUDATSANs), new Action<PHIEUDATSAN>(this.detach_PHIEUDATSANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(4)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(100)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HDTHANHTOAN", Storage="_HDTHANHTOANs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HDTHANHTOAN> HDTHANHTOANs
		{
			get
			{
				return this._HDTHANHTOANs;
			}
			set
			{
				this._HDTHANHTOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUDATSAN", Storage="_PHIEUDATSANs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<PHIEUDATSAN> PHIEUDATSANs
		{
			get
			{
				return this._PHIEUDATSANs;
			}
			set
			{
				this._PHIEUDATSANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDTHANHTOANs(HDTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HDTHANHTOANs(HDTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _Gioitinh;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _SDT;
		
		private decimal _LuongThang;
		
		private EntitySet<HDTHANHTOAN> _HDTHANHTOANs;
		
		private EntitySet<PHIEUDATSAN> _PHIEUDATSANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnLuongThangChanging(decimal value);
    partial void OnLuongThangChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HDTHANHTOANs = new EntitySet<HDTHANHTOAN>(new Action<HDTHANHTOAN>(this.attach_HDTHANHTOANs), new Action<HDTHANHTOAN>(this.detach_HDTHANHTOANs));
			this._PHIEUDATSANs = new EntitySet<PHIEUDATSAN>(new Action<PHIEUDATSAN>(this.attach_PHIEUDATSANs), new Action<PHIEUDATSAN>(this.detach_PHIEUDATSANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(4)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongThang", DbType="Decimal(10,3) NOT NULL")]
		public decimal LuongThang
		{
			get
			{
				return this._LuongThang;
			}
			set
			{
				if ((this._LuongThang != value))
				{
					this.OnLuongThangChanging(value);
					this.SendPropertyChanging();
					this._LuongThang = value;
					this.SendPropertyChanged("LuongThang");
					this.OnLuongThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HDTHANHTOAN", Storage="_HDTHANHTOANs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HDTHANHTOAN> HDTHANHTOANs
		{
			get
			{
				return this._HDTHANHTOANs;
			}
			set
			{
				this._HDTHANHTOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUDATSAN", Storage="_PHIEUDATSANs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<PHIEUDATSAN> PHIEUDATSANs
		{
			get
			{
				return this._PHIEUDATSANs;
			}
			set
			{
				this._PHIEUDATSANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDTHANHTOANs(HDTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HDTHANHTOANs(HDTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDATSAN")]
	public partial class PHIEUDATSAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPDS;
		
		private string _MaKH;
		
		private string _MaSB;
		
		private string _MaNV;
		
		private string _Magio;
		
		private System.Nullable<System.DateTime> _Ngaydatsan;
		
		private System.Nullable<System.DateTime> _Ngaylap;
		
		private string _Trangthai;
		
		private EntitySet<HDTHANHTOAN> _HDTHANHTOANs;
		
		private EntityRef<GIAGIOTHUE> _GIAGIOTHUE;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<SANBONG> _SANBONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPDSChanging(int value);
    partial void OnMaPDSChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaSBChanging(string value);
    partial void OnMaSBChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMagioChanging(string value);
    partial void OnMagioChanged();
    partial void OnNgaydatsanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydatsanChanged();
    partial void OnNgaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaylapChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public PHIEUDATSAN()
		{
			this._HDTHANHTOANs = new EntitySet<HDTHANHTOAN>(new Action<HDTHANHTOAN>(this.attach_HDTHANHTOANs), new Action<HDTHANHTOAN>(this.detach_HDTHANHTOANs));
			this._GIAGIOTHUE = default(EntityRef<GIAGIOTHUE>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._SANBONG = default(EntityRef<SANBONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPDS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPDS
		{
			get
			{
				return this._MaPDS;
			}
			set
			{
				if ((this._MaPDS != value))
				{
					this.OnMaPDSChanging(value);
					this.SendPropertyChanging();
					this._MaPDS = value;
					this.SendPropertyChanged("MaPDS");
					this.OnMaPDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSB", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaSB
		{
			get
			{
				return this._MaSB;
			}
			set
			{
				if ((this._MaSB != value))
				{
					if (this._SANBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSBChanging(value);
					this.SendPropertyChanging();
					this._MaSB = value;
					this.SendPropertyChanged("MaSB");
					this.OnMaSBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magio", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Magio
		{
			get
			{
				return this._Magio;
			}
			set
			{
				if ((this._Magio != value))
				{
					if (this._GIAGIOTHUE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMagioChanging(value);
					this.SendPropertyChanging();
					this._Magio = value;
					this.SendPropertyChanged("Magio");
					this.OnMagioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydatsan", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydatsan
		{
			get
			{
				return this._Ngaydatsan;
			}
			set
			{
				if ((this._Ngaydatsan != value))
				{
					this.OnNgaydatsanChanging(value);
					this.SendPropertyChanging();
					this._Ngaydatsan = value;
					this.SendPropertyChanged("Ngaydatsan");
					this.OnNgaydatsanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylap", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaylap
		{
			get
			{
				return this._Ngaylap;
			}
			set
			{
				if ((this._Ngaylap != value))
				{
					this.OnNgaylapChanging(value);
					this.SendPropertyChanging();
					this._Ngaylap = value;
					this.SendPropertyChanged("Ngaylap");
					this.OnNgaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NVarChar(20)")]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDATSAN_HDTHANHTOAN", Storage="_HDTHANHTOANs", ThisKey="MaPDS", OtherKey="MaPDS")]
		public EntitySet<HDTHANHTOAN> HDTHANHTOANs
		{
			get
			{
				return this._HDTHANHTOANs;
			}
			set
			{
				this._HDTHANHTOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAGIOTHUE_PHIEUDATSAN", Storage="_GIAGIOTHUE", ThisKey="Magio", OtherKey="Magio", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public GIAGIOTHUE GIAGIOTHUE
		{
			get
			{
				return this._GIAGIOTHUE.Entity;
			}
			set
			{
				GIAGIOTHUE previousValue = this._GIAGIOTHUE.Entity;
				if (((previousValue != value) 
							|| (this._GIAGIOTHUE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAGIOTHUE.Entity = null;
						previousValue.PHIEUDATSANs.Remove(this);
					}
					this._GIAGIOTHUE.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATSANs.Add(this);
						this._Magio = value.Magio;
					}
					else
					{
						this._Magio = default(string);
					}
					this.SendPropertyChanged("GIAGIOTHUE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUDATSAN", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUDATSANs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATSANs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUDATSAN", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUDATSANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATSANs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANBONG_PHIEUDATSAN", Storage="_SANBONG", ThisKey="MaSB", OtherKey="MaSB", IsForeignKey=true)]
		public SANBONG SANBONG
		{
			get
			{
				return this._SANBONG.Entity;
			}
			set
			{
				SANBONG previousValue = this._SANBONG.Entity;
				if (((previousValue != value) 
							|| (this._SANBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANBONG.Entity = null;
						previousValue.PHIEUDATSANs.Remove(this);
					}
					this._SANBONG.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATSANs.Add(this);
						this._MaSB = value.MaSB;
					}
					else
					{
						this._MaSB = default(string);
					}
					this.SendPropertyChanged("SANBONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDTHANHTOANs(HDTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATSAN = this;
		}
		
		private void detach_HDTHANHTOANs(HDTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATSAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANBONG")]
	public partial class SANBONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSB;
		
		private string _TenSB;
		
		private string _Dientich;
		
		private EntitySet<PHIEUDATSAN> _PHIEUDATSANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSBChanging(string value);
    partial void OnMaSBChanged();
    partial void OnTenSBChanging(string value);
    partial void OnTenSBChanged();
    partial void OnDientichChanging(string value);
    partial void OnDientichChanged();
    #endregion
		
		public SANBONG()
		{
			this._PHIEUDATSANs = new EntitySet<PHIEUDATSAN>(new Action<PHIEUDATSAN>(this.attach_PHIEUDATSANs), new Action<PHIEUDATSAN>(this.detach_PHIEUDATSANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSB", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSB
		{
			get
			{
				return this._MaSB;
			}
			set
			{
				if ((this._MaSB != value))
				{
					this.OnMaSBChanging(value);
					this.SendPropertyChanging();
					this._MaSB = value;
					this.SendPropertyChanged("MaSB");
					this.OnMaSBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSB", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenSB
		{
			get
			{
				return this._TenSB;
			}
			set
			{
				if ((this._TenSB != value))
				{
					this.OnTenSBChanging(value);
					this.SendPropertyChanging();
					this._TenSB = value;
					this.SendPropertyChanged("TenSB");
					this.OnTenSBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dientich", DbType="NVarChar(20)")]
		public string Dientich
		{
			get
			{
				return this._Dientich;
			}
			set
			{
				if ((this._Dientich != value))
				{
					this.OnDientichChanging(value);
					this.SendPropertyChanging();
					this._Dientich = value;
					this.SendPropertyChanged("Dientich");
					this.OnDientichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANBONG_PHIEUDATSAN", Storage="_PHIEUDATSANs", ThisKey="MaSB", OtherKey="MaSB")]
		public EntitySet<PHIEUDATSAN> PHIEUDATSANs
		{
			get
			{
				return this._PHIEUDATSANs;
			}
			set
			{
				this._PHIEUDATSANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.SANBONG = this;
		}
		
		private void detach_PHIEUDATSANs(PHIEUDATSAN entity)
		{
			this.SendPropertyChanging();
			entity.SANBONG = null;
		}
	}
}
#pragma warning restore 1591
